require:
  - rubocop-rake
AllCops:
  TargetRubyVersion: 3.1.x
  EnabledByDefault: true

# Customize rules
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/StaticClass:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/Copyright:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
Style/MissingElse:
  Enabled: false
Style/ConstantVisibility:
  Enabled: false
Style/EmptyElse:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/LineLength:
  Enabled: false
Lint/ConstantResolution:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: false
Bundler/GemComment:
  Enabled: false
